--
-- DBL_APICLOUDDB  (Database Link) 
--
CREATE PUBLIC DATABASE LINK DBL_APICLOUDDB
 CONNECT TO INS_WEB
 IDENTIFIED BY <PWD>
 USING 'apiclouddb';


--
-- DBL_SMSDB  (Database Link) 
--
CREATE PUBLIC DATABASE LINK DBL_SMSDB
 CONNECT TO SANDHANI
 IDENTIFIED BY <PWD>
 USING '192.168.1.150:1521/orcl';



--
-- DBL_DMGDB  (Database Link) 
--
CREATE DATABASE LINK DBL_DMGDB
 CONNECT TO INS
 IDENTIFIED BY <PWD>
 USING 'dmgdb';


--
-- DBL_SLIC  (Database Link) 
--
CREATE DATABASE LINK DBL_SLIC
 CONNECT TO INS
 IDENTIFIED BY <PWD>
 USING 'SLIC';


--
-- DBL_SMSDB1  (Database Link) 
--
CREATE DATABASE LINK DBL_SMSDB1
 CONNECT TO SANDHANI
 IDENTIFIED BY <PWD>
 USING 'SMSDB';


--
-- DBL_TANY  (Database Link) 
--
CREATE DATABASE LINK DBL_TANY
 CONNECT TO JOYNAL
 IDENTIFIED BY <PWD>
 USING 'TANY';


--
-- DBL_WEBAPIDB  (Database Link) 
--
CREATE DATABASE LINK DBL_WEBAPIDB
 CONNECT TO INS_WEB
 IDENTIFIED BY <PWD>
 USING 'WEBAPIDB';


