--
-- EXAMPLE  (Tablespace) 
--
CREATE TABLESPACE EXAMPLE DATAFILE 
  '/u01/app/oracle/oradata/slicldb/example01.dbf' SIZE 200M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
NOLOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_ACC_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_ACC_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_ACC_TBS.dbf' SIZE 21880M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
  '/u01/app/oracle/oradata/slicldb/INS_ACC_TBS2.dbf' SIZE 32020M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_CLM_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_CLM_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_CLM_TBS.dbf' SIZE 16890M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_COM_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_COM_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_COM_TBS.dbf' SIZE 10240M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_DA_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_DA_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_DA_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_DUE_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_DUE_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_DUE_TBS.dbf' SIZE 23580M AUTOEXTEND ON NEXT 100M MAXSIZE 32767M,
  '/u01/app/oracle/oradata/slicldb/INS_DUE_TBS2.dbf' SIZE 23680M AUTOEXTEND ON NEXT 100M MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_GPI_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_GPI_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_GPI_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_HIST_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_HIST_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_HIST_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_HR_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_HR_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_HR_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_INDX_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_INDX_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_INDX_TBS.dbf' SIZE 30720M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_MIS_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_MIS_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_MIS_TBS.dbf' SIZE 3048M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_NB_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_NB_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_NB_TBS.dbf' SIZE 20480M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
  '/u01/app/oracle/oradata/slicldb/INS_NB_TBS3.dbf' SIZE 20480M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_PAY_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_PAY_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_PAY_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE 32767M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_PIR_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_PIR_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_PIR_TBS.dbf' SIZE 5120M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_PL_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_PL_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_PL_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_REI_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_REI_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_REI_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_SEC_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_SEC_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_SEC_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_SER_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_SER_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_SER_TBS.dbf' SIZE 6605M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_SUR_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_SUR_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_SUR_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_USERS_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_USERS_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_USERS_TBS' SIZE 33554416K AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_UTL_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_UTL_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_UTL_TBS.dbf' SIZE 1024M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_UW_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_UW_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_UW_TBS.dbf' SIZE 10240M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_VAL_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_VAL_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_VAL_TBS.dbf' SIZE 5520M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED,
  '/u01/app/oracle/oradata/slicldb/INS_VAL_TBS1.dbf' SIZE 2048M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- INS_WEB_TBS  (Tablespace) 
--
CREATE TABLESPACE INS_WEB_TBS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/INS_WEB_TBS.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- SYSAUX  (Tablespace) 
--
CREATE TABLESPACE SYSAUX DATAFILE 
  '/u01/app/oracle/oradata/slicldb/sysaux01.dbf' SIZE 5315M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- SYSTEM  (Tablespace) 
--
CREATE TABLESPACE SYSTEM DATAFILE 
  '/u01/app/oracle/oradata/slicldb/system01.dbf' SIZE 10312M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
FLASHBACK ON;


--
-- TEMP  (Tablespace) 
--
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  '/u01/app/oracle/oradata/slicldb/temp01.dbf' SIZE 32767M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


--
-- UNDOTBS1  (Tablespace) 
--
CREATE UNDO TABLESPACE UNDOTBS1 DATAFILE 
  '/u01/app/oracle/oradata/slicldb/undotbs01.dbf' SIZE 30985M AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
ONLINE
RETENTION NOGUARANTEE
BLOCKSIZE 8K
FLASHBACK ON;


--
-- USERS  (Tablespace) 
--
CREATE TABLESPACE USERS DATAFILE 
  '/u01/app/oracle/oradata/slicldb/users01.dbf' SIZE 17536768K AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


